// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gatitosEtl.Data.context;

#nullable disable

namespace gatitosEtl.Data.Migrations
{
    [DbContext(typeof(DbGatitosContext))]
    [Migration("20260415050835_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("gatitosEtl.Models.DIMS.DimCiudad", b =>
                {
                    b.Property<int>("id_ciudad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_ciudad"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id_ciudad");

                    b.HasIndex("nombre")
                        .IsUnique();

                    b.ToTable("DimCiudades");
                });

            modelBuilder.Entity("gatitosEtl.Models.DIMS.DimFecha", b =>
                {
                    b.Property<int>("id_fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_fecha"));

                    b.Property<int>("anio")
                        .HasColumnType("int");

                    b.Property<int>("dia")
                        .HasColumnType("int");

                    b.Property<int>("mes")
                        .HasColumnType("int");

                    b.HasKey("id_fecha");

                    b.HasIndex("dia", "mes", "anio")
                        .IsUnique();

                    b.ToTable("DimFechas");
                });

            modelBuilder.Entity("gatitosEtl.Models.DIMS.DimGato", b =>
                {
                    b.Property<int>("id_gato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_gato"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("raza")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id_gato");

                    b.ToTable("DimGatos");
                });

            modelBuilder.Entity("gatitosEtl.Models.DIMS.DimPersona", b =>
                {
                    b.Property<int>("id_persona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_persona"));

                    b.Property<int>("idCiudad")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id_persona");

                    b.HasIndex("idCiudad");

                    b.ToTable("DimPersonas");
                });

            modelBuilder.Entity("gatitosEtl.Models.DIMS.DimPersona", b =>
                {
                    b.HasOne("gatitosEtl.Models.DIMS.DimCiudad", null)
                        .WithMany()
                        .HasForeignKey("idCiudad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
